gate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('records.urls') )
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

records/urls.py
from django.urls import path
from . import views

app_name = 'records'
urlpatterns = [
    path('', views.login, name='login'),
    path('overview/', views.overview, name='overview'),
    path('record-visitor/', views.record_visitor, name='record_visitor'),
    path('check-out-visitor/<int:visitor_id>/', views.check_out_visitor, name='check_out_visitor'),
    path('visitor-list/', views.visitor_list, name='visitors'),
    path('visitor-list/details/<int:visitor_id>/', views.details, name='details'),
    path('approve/<int:visitor_id>/', views.approve_visitor, name='approve_visitor'),
    path('movements/', views.movements, name='movements'),
    path('search/', views.search_visitors, name='search_visitors'),
    path('logout/', views.logout_view, name='logout'),
    path('checkout-visitor/', views.checkout_visitor, name='checkout_visitor'),  # New URL pattern for card reader checkout
    path('card-reader-interaction/', views.card_reader_interaction, name='card_reader_interaction'),  # New URL pattern for card reader interaction
]

records/models.py
from django.db import models

# Create your models here.
class WaitingList(models.Model):
    id_passport_nbr = models.CharField(max_length=100, primary_key=True)
    first_name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    organization = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    country_of_origin = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    mobile_phone = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.surname}"
    
    
class Visitor(models.Model):
    id_passport_nbr = models.CharField(max_length=100, primary_key=True)
    first_name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    organization = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    country_of_origin = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    mobile_phone = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.surname}"

class Card(models.Model):
    name= models.CharField(max_length=50)
    number = models.IntegerField(max_length=50)

    def __str__(self):
        return self.number


class Movement(models.Model):
    # visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE, to_field='id_passport_nbr')
    visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE, to_field='id_passport_nbr', related_name='movements')
    purpose = models.CharField(max_length=200)
    time_in = models.DateTimeField()
    time_out = models.DateTimeField(blank=True, null=True)
    devices = models.CharField(max_length=200, blank=True)
    comment = models.TextField(blank=True)
    card = models.OneToOneField(Card, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.visitor} - Time In: {self.time_in} - Time Out: {self.time_out}"

records/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from .models import *
from datetime import datetime
from django.utils import timezone
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import get_object_or_404
from django.contrib import messages
from .decorators import *
from django.contrib.auth import authenticate, login as auth_login, logout

def login(request):  
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('records:record_visitor')  # Redirect to the desired page after successful login
        else:
            messages.error(request, 'Invalid username or password.')
            return redirect('records:login')
    return render(request, 'cre/login.html')

def logout_view(request):
    logout(request)
    return redirect('records:login') 

def overview(request):
  template = loader.get_template('records/test.html')
  return HttpResponse(template.render())

# @login_required
# @group_required('Security')
def record_visitor(request):
    if request.method == 'POST':
        form_data = request.POST
        waitingList = WaitingList(
            id_passport_nbr=form_data['id_passport_nbr'],
            first_name=form_data['first_name'],
            surname=form_data['surname'],
            organization=form_data['organization'],
            position=form_data['position'],
            country_of_origin=form_data['country_of_origin'],
            email=form_data['email'],
            address=form_data['address'],
            mobile_phone=form_data['mobile_phone'],
            # purpose=form_data['purpose'],
            # devices=form_data['devices'],
            # time_in=datetime.now()
        )
        waitingList.save()
        messages.success(request, 'Visitor recorded successfully in WaitingList.')
        return redirect('records:record_visitor')
    return render(request, 'records/test.html')

@login_required
def check_out_visitor(request, visitor_id):
    # movement = Movement.objects.get(pk=visitor_id)
    movement = get_object_or_404(Movement, visitor__id_passport_nbr=visitor_id, time_out__isnull=True)
    # if movement.time_out is None:
    movement.time_out = datetime.now()
    movement.save()
    messages.success(request, 'Visitor checked out successfully.')
    return redirect('records:movements')
def checkout_visitor(request):
    if request.method == 'POST':
        card_number = request.POST.get('cardNumber')
        try:
            visitor = Visitor.objects.get(card__number=card_number)
            movement = Movement.objects.create(
                visitor=visitor,
                time_in=visitor.movements.latest('time_in').time_in,
                time_out=timezone.now(),
            )
            return JsonResponse({'success': True})
        except Visitor.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Visitor not found'})
    return JsonResponse({'success': False, 'message': 'Invalid request'})

def card_reader_interaction(request):
    if request.method == 'POST':
        card_number = request.POST.get('cardNumber')
        try:
            visitor = Visitor.objects.get(card__number=card_number)
            movement = Movement.objects.create(
                visitor=visitor,
                time_in=visitor.movements.latest('time_in').time_in,
                time_out=timezone.now(),
            )
            return JsonResponse({'success': True})
        except Visitor.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Visitor not found'})
    return JsonResponse({'success': False, 'message': 'Invalid request'})

@login_required
# @group_required('Supervisor')
# @group_required('Security')
def visitor_list(request):
    waitinglist=WaitingList.objects.all().values()
    template = loader.get_template('records/visitor_list.html')
    context = {'waitinglist': waitinglist }
    return HttpResponse(template.render(context, request))

# details of a visitor
def details(request, visitor_id):
    detailedVisitor = get_object_or_404(WaitingList, id_passport_nbr=visitor_id)
    
    # Handle form submission for visitor approval
    if request.method == 'POST':
        # Get the form data
        purpose = request.POST.get('purpose')
        comment = request.POST.get('comment')
        card_id = request.POST.get('card')
        devices = request.POST.get('devices')
        
         # Create a new Visitor instance
        visitor = Visitor(
            id_passport_nbr=detailedVisitor.id_passport_nbr,
            first_name=detailedVisitor.first_name,
            surname=detailedVisitor.surname,
            organization=detailedVisitor.organization,
            position=detailedVisitor.position,
            country_of_origin=detailedVisitor.country_of_origin,
            email=detailedVisitor.email,
            address=detailedVisitor.address,
            mobile_phone=detailedVisitor.mobile_phone
        )
        # Save the Visitor instance
        visitor.save()
        # Create a new Movement instance
        movement = Movement(
            visitor=visitor,
            purpose=purpose,
            devices=devices,
            time_in=timezone.now(),
            comment=comment
        )
        
        # Set the card if selected
        if card_id:
            card = get_object_or_404(Card, pk=card_id)
            movement.card = card
        
        # Save the Movement instance
        movement.save()
        
        # Redirect or render a success message
        detailedVisitor.delete()
        return redirect('records:visitors')
    # Render the details template with the visitor's information
    context = {
        'detailedVisitor': detailedVisitor,
    }
    return render(request, 'records/visitor_list.html', context)
#   detailedVisitor = WaitingList.objects.get(id_passport_nbr=id)
#   template = loader.get_template('records/details.html')
#   context = {
#     'detailedVisitor': detailedVisitor,
#   }
#   return HttpResponse(template.render(context, request))

@login_required
def search_visitors(request):
    query = request.GET.get('query', '')
    visitors = Visitor.objects.filter(first_name__icontains=query)
    context = {'visitors': visitors}
    html = render_to_string('records/search_results.html', context)
    return JsonResponse({'html': html})



def approve_visitor(request, visitor_id):
    # Retrieve the visitor from the WaitingList
    waiting_visitor = WaitingList.objects.get(id_passport_nbr=visitor_id)

    # Create a new Visitor instance with the data from the WaitingList
    visitor = Visitor(
        id_passport_nbr=waiting_visitor.id_passport_nbr,
        first_name=waiting_visitor.first_name,
        surname=waiting_visitor.surname,
        organization=waiting_visitor.organization,
        position=waiting_visitor.position,
        country_of_origin=waiting_visitor.country_of_origin,
        email=waiting_visitor.email,
        address=waiting_visitor.address,
        mobile_phone=waiting_visitor.mobile_phone
    )

    # Save the new Visitor instance
    visitor.save()

    # Delete the corresponding entry from the WaitingList
    waiting_visitor.delete()
    messages.success(request, 'Visitor checked out successfully.')
    return redirect('records:visitors')


def movements(request):
    # movements = Movement.objects.all()
    checked_in_visitors = Movement.objects.filter(time_out__isnull=True)
    checked_out_visitors = Movement.objects.exclude(time_out__isnull=True)

    # Order checked-in visitors by most recent first
    checked_in_visitors = checked_in_visitors.order_by('-id')

    # Order checked-out visitors by most recent checked-out time
    checked_out_visitors = checked_out_visitors.order_by('-time_out')

    movements = list(checked_in_visitors) + list(checked_out_visitors)
    context = {'movements': movements}
    return render(request, 'records/movement.html', context)

records/templates/records/details.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<main class="main-wrapper">
<header class="header">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-5 col-md-5 col-6">
          <div class="header-left d-flex align-items-center">
            <div class="menu-toggle-btn mr-20">
              <button
                id="menu-toggle"
                class="main-btn primary-btn btn-hover"
              >
                <i class="lni lni-chevron-left me-2"></i> Menu
              </button>
            </div>
            <div class="header-search d-none d-md-flex">
              <form action="#">
                <input type="text" placeholder="Search..." />
                <button><i class="lni lni-search-alt"></i></button>
              </form>
            </div>
          </div>
        </div>
        <div class="col-lg-7 col-md-7 col-6">
          <div class="header-right">
            <!-- notification start -->
            <div class="notification-box ml-15 d-none d-md-flex">
              <!-- <button
                class="dropdown-toggle"
                type="button"
                id="notification"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <i class="lni lni-alarm"></i>
                <span>2</span>
              </button> -->
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="notification"
              >
                <li>
                  <a href="#0">
                    <div class="image">
                      <img src="{% static 'assets/images/lead/lead-6.png' %}" alt="" />
                    </div>
                    <div class="content">
                      <h6>
                        John Doe
                        <span class="text-regular">
                          comment on a product.
                        </span>
                      </h6>
                      <p>
                        Lorem ipsum dolor sit amet, consect etur adipiscing
                        elit Vivamus tortor.
                      </p>
                      <span>10 mins ago</span>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#0">
                    <div class="image">
                      <img src="{% static 'assets/images/lead/lead-1.png' %}" alt="" />
                    </div>
                    <div class="content">
                      <h6>
                        Jonathon
                        <span class="text-regular">
                          like on a product.
                        </span>
                      </h6>
                      <p>
                        Lorem ipsum dolor sit amet, consect etur adipiscing
                        elit Vivamus tortor.
                      </p>
                      <span>10 mins ago</span>
                    </div>
                  </a>
                </li>
              </ul>
            </div>
           
            <!-- profile start -->
            <div class="profile-box ml-15">
              <button
                class="dropdown-toggle bg-transparent border-0"
                type="button"
                id="profile"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <div class="profile-info">
                  <div class="info">
                    {% if user.is_authenticated %}
                    <h6>{{ user.username }}</h6>
                    {% endif %}
                    <div class="image">
                      <img
                        src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/BMW_logo_%28gray%29.svg/270px-BMW_logo_%28gray%29.svg.png"
                        alt=""
                      />
                      <span class="status"></span>
                    </div>
                  </div>
                </div>
                <i class="lni lni-chevron-down"></i>
              </button>
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="profile"
              >
                <li>
                  <a href="#0">
                    <i class="lni lni-user"></i> View Profile
                  </a>
                </li>
                <li>
                  <a href="#0">
                    <i class="lni lni-alarm"></i> Notifications
                  </a>
                </li>
                <li>
                  <a href="#0"> <i class="lni lni-inbox"></i> Messages </a>
                </li>
                <li>
                  <a href="#0"> <i class="lni lni-cog"></i> Settings </a>
                </li>
                <li>
                  <a href="{% url 'records:logout' %}"> <i class="lni lni-exit"></i> Sign Out </a>
                </li>
              </ul>
            </div>
            <!-- profile end -->
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- ========== header end ========== -->
<section class="table-components">
    <!-- <div class="container-fluid"> -->
        <div class="tables-wrapper">
        <div class="row">
            <div class="col-lg-12">
            <div class="card-style mb-30">
                <h1 class="mb-10">Aprove Visitor</h1>
                <p class="text-sm mb-20"></p>
                <div class="table-wrapper table-responsive">
                    <!-- Display existing visitor data -->

                    <p>First Name: {{ detailedVisitor.first_name }}</p>
                    <p>Surname: {{ detailedVisitor.surname }}</p>

                    <!-- Approval form -->
                    <form method="POST" action="{% url 'records:approve_visitor' visitor_id=detailedVisitor.id_passport_nbr %}">
                    {% csrf_token %}
                    <!-- Additional fields for data collection -->
                    <label for="purpose">Purpose:</label>
                    <input type="text" name="purpose">
                    <label for="comment">Comment:</label>
                    <textarea name="comment"></textarea>
                    <label for="devices">devices:</label>
                    <textarea name="devices"></textarea>
                    <label for="card">Card:</label>
                    <select name="card">
                        <option value="">Select Card</option>
                        {% for card in cards %}
                        <option value="{{ card.id }}">{{ card.name }}</option>
                        {% endfor %}
                    </select>
                    <!-- Submit button -->
                    <input type="submit" value="Approve">
                    </form>

                <!-- end table -->
                </div>
            </div>
            <!-- end card -->
            </div>
    <!-- end col -->
    <!-- </div> -->
    </div>
    </div>
</section>
</main>

{% endblock content %}

records/templates/records/movement.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<div class="modal" id="cardReaderModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Card Reader Animation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <!-- Replace 'YOUR_ANIMATED_SVG_LINK' with the actual link to your animated SVG -->
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/BMW_logo_%28gray%29.svg/270px-BMW_logo_%28gray%29.svg.png" alt="Card Reader Animation" />
      </div>
      <input type="text" id="card-reader-input" >

    </div>
  </div>
</div>
<main class="main-wrapper">
<header class="header">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-5 col-md-5 col-6">
          <div class="header-left d-flex align-items-center">
            <div class="menu-toggle-btn mr-20">
              <button
                id="menu-toggle"
                class="main-btn primary-btn btn-hover"
              >
                <i class="lni lni-chevron-left me-2"></i> Menu
              </button>
            </div>
            <div class="header-search d-none d-md-flex">
              <form action="#">
                <input type="text" placeholder="Search..." />
                <button><i class="lni lni-search-alt"></i></button>
              </form>
            </div>
          </div>
        </div>
        <div class="col-lg-7 col-md-7 col-6">
          <div class="header-right">
            <!-- notification start -->
            <div class="notification-box ml-15 d-none d-md-flex">
              <!-- <button
                class="dropdown-toggle"
                type="button"
                id="notification"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <i class="lni lni-alarm"></i>
                <span>2</span>
              </button> -->
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="notification"
              >
                <li>
                  <a href="#0">
                    <div class="image">
                      <img src="{% static 'assets/images/lead/lead-6.png' %}" alt="" />
                    </div>
                    <div class="content">
                      <h6>
                        John Doe
                        <span class="text-regular">
                          comment on a product.
                        </span>
                      </h6>
                      <p>
                        Lorem ipsum dolor sit amet, consect etur adipiscing
                        elit Vivamus tortor.
                      </p>
                      <span>10 mins ago</span>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#0">
                    <div class="image">
                      <img src="{% static 'assets/images/lead/lead-1.png' %}" alt="" />
                    </div>
                    <div class="content">
                      <h6>
                        Jonathon
                        <span class="text-regular">
                          like on a product.
                        </span>
                      </h6>
                      <p>
                        Lorem ipsum dolor sit amet, consect etur adipiscing
                        elit Vivamus tortor.
                      </p>
                      <span>10 mins ago</span>
                    </div>
                  </a>
                </li>
              </ul>
            </div>
           
            <!-- profile start -->
            <div class="profile-box ml-15">
              <button
                class="dropdown-toggle bg-transparent border-0"
                type="button"
                id="profile"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <div class="profile-info">
                  <div class="info">
                    {% if user.is_authenticated %}
                    <h6>{{ user.username }}</h6>
                    {% endif %}
                    <div class="image">
                      <img
                        src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/BMW_logo_%28gray%29.svg/270px-BMW_logo_%28gray%29.svg.png"
                        alt=""
                      />
                      <span class="status"></span>
                    </div>
                  </div>
                </div>
                <i class="lni lni-chevron-down"></i>
              </button>
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="profile"
              >
                <li>
                  <a href="#0">
                    <i class="lni lni-user"></i> View Profile
                  </a>
                </li>
                <li>
                  <a href="#0">
                    <i class="lni lni-alarm"></i> Notifications
                  </a>
                </li>
                <li>
                  <a href="#0"> <i class="lni lni-inbox"></i> Messages </a>
                </li>
                <li>
                  <a href="#0"> <i class="lni lni-cog"></i> Settings </a>
                </li>
                <li>
                  <a href="{% url 'records:logout' %}"> <i class="lni lni-exit"></i> Sign Out </a>
                </li>
              </ul>
            </div>
            <!-- profile end -->
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- ========== header end ========== -->
   <!-- Add the big button for card reader interaction -->
   <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card-style mb-30">
          <button id="card-reader-btn" class="main-btn primary-btn btn-hover">
            Tap Card to Check Out
          </button>
        </div>
      </div>
    </div>
  </div>
<section class="table-components">
    <!-- <div class="container-fluid"> -->
        <div class="tables-wrapper">
        <div class="row">
            <div class="col-lg-12">
            <div class="card-style mb-30">
                <h1 class="mb-10">Visitor List</h1>
                <p class="text-sm mb-20"></p>
                <div class="table-wrapper table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th><h6>Name</h6></th>
                        <th><h6>ID</h6></th>
                        <th><h6>Email</h6></th>
                        <th><h6>Phone Number</h6></th>
                        <th><h6>Organization</h6></th>
                        <th><h6>Card Number</h6></th>
                        <th><h6>Time In</h6></th>
                        <th><h6>Time Out</h6></th>
                    </tr>
                    <!-- end table row-->
                    </thead>
                    <tbody>
                    {% include 'partials/alerts.html' %}
                    {% for movement in movements %}        
                    <tr>
                        <td class="min-width">
                            <p>{{ movement.visitor.first_name }}</p>
                        </td>
                        <td class="min-width">
                        <p>{{ movement.visitor.id_passport_nbr}}</p>
                        </td>
                        <td class="min-width">
                        <p>{{ movement.visitor.email }}</p>
                        </td>
                        <td class="min-width">
                            <p>{{ movement.visitor.mobile_phone }}</p>
                        </td>
                        <td class="min-width">
                          <p>{{ movement.visitor.organization }}</p>
                        </td>
                        <td class="min-width">
                          <p>{{ movement.card.name }}</p>
                        </td>
                        <td class="min-width">
                          <p>{{ movement.time_in }}</p>
                        </td>
                        <td>
                          {% if movement.time_out %}
                          <p>{{ movement.time_out }}</p>
                              <!-- <h6 class="main-btn success-btn rounded-full btn-hover btn-sm">Checked out</h6> -->
                          {% else %}
                          <form method="post" action="{% url 'records:check_out_visitor' visitor_id=movement.visitor.id_passport_nbr %}">
                              {% csrf_token %}
                              <input type="submit" class="main-btn active-btn rounded-full btn-hover btn-sm" value="Check Out">
                          </form>
                          {% endif %} 
                        </td>
                    </tr>
                    {% endfor %}
                   
                   
                    <!-- end table row -->
                    </tbody>
                </table>
                <!-- end table -->
                </div>
            </div>
            <!-- end card -->
            </div>
    <!-- end col -->
    <!-- </div> -->
    </div>
    </div>
</section>
</main>

{% endblock content %}

records/templates/records/record_visitor.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Register</h1>
    <form method="post" action="{% url 'records:record_visitor' %}">
        {% csrf_token %}
        <label for="first_name">First Name:</label>
        <input type="text" name="first_name" id="first_name" required>
        <br>
        <label for="surname">Surname:</label>
        <input type="text" name="surname" id="surname" required>
        <br>
        <label for="organization">Organization:</label>
        <input type="text" name="organization" id="organization" required>
        <br>
        <label for="position">Position:</label>
        <input type="text" name="position" id="position" required>
        <br>
        <label for="country_of_origin">Country of Origin:</label>
        <input type="text" name="country_of_origin" id="country_of_origin" required>
        <br>
        <label for="id_passport_nbr">ID/Passport Number:</label>
        <input type="text" name="id_passport_nbr" id="id_passport_nbr" required>
        <br>
        <label for="email">Email:</label>
        <input type="email" name="email" id="email" required>
        <br>
        <label for="address">Address:</label>
        <textarea name="address" id="address" required></textarea>
        <br>
        <label for="mobile_phone">Mobile Phone:</label>
        <input type="text" name="mobile_phone" id="mobile_phone" required>
        <br>
        <label for="devices">Devices:</label>
        <input type="text" name="devices" id="devices" required>
        <br>
        <input type="submit" value="Submit">
      </form>
      
</body>
</html>

records/templates/records/search_results.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for visitor in visitors %}
    <div>
        <span>{{ visitor.first_name }} {{ visitor.surname }}</span>
        <button class="checkout-btn" data-visitor-id="{{ visitor.id }}">Check Out</button>
    </div>
    {% empty %}
    <p>No results found.</p>
    {% endfor %}
    

</body>
</html>

records/templates/records/test2.html
<!DOCTYPE html>
<html>
<head>
    <title>Movement Records</title>
</head>
<body>
    <h1>Movement Records</h1>
    <table border="1">
        <tr>
            <th>Visitor Name</th>
            <th>Visitor Organization</th>
            <th>Purpose</th>
            <th>Time In</th>
            <th>Time Out</th>
            <th>Devices</th>
            <th>Comment</th>
            <th>Card</th>
        </tr>
        {% for movement in movements %}
        <tr>
            <td>{{ movement.visitor.first_name }} {{ movement.visitor.surname }}</td>
            <td>{{ movement.visitor.organization }}</td>
            <td>{{ movement.purpose }}</td>
            <td>{{ movement.time_in }}</td>
            <td>{{ movement.time_out }}</td>
            <td>{{ movement.devices }}</td>
            <td>{{ movement.comment }}</td>
           
        </tr>
        {% endfor %}
    </table>

    <h2>RFID Cards</h2>
    <table border="1">
        <tr>
            <th>Name</th>
            <th>Number</th>
        </tr>
        {% for card in cards %}
        <tr>
            <td>{{ card.name }}</td>
            <td>{{ card.number }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>