gate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('records.urls') )
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

records/urls.py
from django.urls import path
from . import views

app_name = 'records'
urlpatterns = [
    path('', views.login, name='login'),
    path('overview/', views.overview, name='overview'),
    path('record-visitor/', views.record_visitor, name='record_visitor'),
    path('check-out-visitor/<int:visitor_id>/', views.check_out_visitor, name='check_out_visitor'),
    path('visitor-list/', views.visitor_list, name='visitors'),
    path('visitor-list/details/<int:visitor_id>/', views.details, name='details'),
    path('approve/<int:visitor_id>/', views.approve_visitor, name='approve_visitor'),
    path('movements/', views.movements, name='movements'),
    path('search/', views.search_visitors, name='search_visitors'),
    path('logout/', views.logout_view, name='logout'),
    path('checkout-visitor/', views.checkout_visitor, name='checkout_visitor'),  # New URL pattern for card reader checkout
    path('card-reader-interaction/', views.card_reader_interaction, name='card_reader_interaction'),  # New URL pattern for card reader interaction
]

records/models.py
from django.db import models

# Create your models here.
class WaitingList(models.Model):
    id_passport_nbr = models.CharField(max_length=100, primary_key=True)
    first_name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    organization = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    country_of_origin = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    mobile_phone = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.surname}"
    
    
class Visitor(models.Model):
    id_passport_nbr = models.CharField(max_length=100, primary_key=True)
    first_name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    organization = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    country_of_origin = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    mobile_phone = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.surname}"

class Card(models.Model):
    name= models.CharField(max_length=50)
    number = models.IntegerField(max_length=50)

    def __str__(self):
        return self.number


class Movement(models.Model):
    # visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE, to_field='id_passport_nbr')
    visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE, to_field='id_passport_nbr', related_name='movements')
    purpose = models.CharField(max_length=200)
    time_in = models.DateTimeField()
    time_out = models.DateTimeField(blank=True, null=True)
    devices = models.CharField(max_length=200, blank=True)
    comment = models.TextField(blank=True)
    card = models.OneToOneField(Card, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.visitor} - Time In: {self.time_in} - Time Out: {self.time_out}"

records/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from .models import *
from datetime import datetime
from django.utils import timezone
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import get_object_or_404
from django.contrib import messages
from .decorators import *
from django.contrib.auth import authenticate, login as auth_login, logout

def login(request):  
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('records:record_visitor')  # Redirect to the desired page after successful login
        else:
            messages.error(request, 'Invalid username or password.')
            return redirect('records:login')
    return render(request, 'cre/login.html')

def logout_view(request):
    logout(request)
    return redirect('records:login') 

def overview(request):
  template = loader.get_template('records/test.html')
  return HttpResponse(template.render())

# @login_required
# @group_required('Security')
def record_visitor(request):
    if request.method == 'POST':
        form_data = request.POST
        waitingList = WaitingList(
            id_passport_nbr=form_data['id_passport_nbr'],
            first_name=form_data['first_name'],
            surname=form_data['surname'],
            organization=form_data['organization'],
            position=form_data['position'],
            country_of_origin=form_data['country_of_origin'],
            email=form_data['email'],
            address=form_data['address'],
            mobile_phone=form_data['mobile_phone'],
            # purpose=form_data['purpose'],
            # devices=form_data['devices'],
            # time_in=datetime.now()
        )
        waitingList.save()
        messages.success(request, 'Visitor recorded successfully in WaitingList.')
        return redirect('records:record_visitor')
    return render(request, 'records/test.html')

@login_required
def check_out_visitor(request, visitor_id):
    # movement = Movement.objects.get(pk=visitor_id)
    movement = get_object_or_404(Movement, visitor__id_passport_nbr=visitor_id, time_out__isnull=True)
    # if movement.time_out is None:
    movement.time_out = datetime.now()
    movement.save()
    messages.success(request, 'Visitor checked out successfully.')
    return redirect('records:movements')
def checkout_visitor(request):
    if request.method == 'POST':
        card_number = request.POST.get('cardNumber')
        try:
            visitor = Visitor.objects.get(card__number=card_number)
            movement = Movement.objects.create(
                visitor=visitor,
                time_in=visitor.movements.latest('time_in').time_in,
                time_out=timezone.now(),
            )
            return JsonResponse({'success': True})
        except Visitor.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Visitor not found'})
    return JsonResponse({'success': False, 'message': 'Invalid request'})

def card_reader_interaction(request):
    if request.method == 'POST':
        card_number = request.POST.get('cardNumber')
        try:
            visitor = Visitor.objects.get(card__number=card_number)
            movement = Movement.objects.create(
                visitor=visitor,
                time_in=visitor.movements.latest('time_in').time_in,
                time_out=timezone.now(),
            )
            return JsonResponse({'success': True})
        except Visitor.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Visitor not found'})
    return JsonResponse({'success': False, 'message': 'Invalid request'})

@login_required
# @group_required('Supervisor')
# @group_required('Security')
def visitor_list(request):
    waitinglist=WaitingList.objects.all().values()
    template = loader.get_template('records/visitor_list.html')
    context = {'waitinglist': waitinglist }
    return HttpResponse(template.render(context, request))

# details of a visitor
def details(request, visitor_id):
    detailedVisitor = get_object_or_404(WaitingList, id_passport_nbr=visitor_id)
    
    # Handle form submission for visitor approval
    if request.method == 'POST':
        # Get the form data
        purpose = request.POST.get('purpose')
        comment = request.POST.get('comment')
        card_id = request.POST.get('card')
        devices = request.POST.get('devices')
        
         # Create a new Visitor instance
        visitor = Visitor(
            id_passport_nbr=detailedVisitor.id_passport_nbr,
            first_name=detailedVisitor.first_name,
            surname=detailedVisitor.surname,
            organization=detailedVisitor.organization,
            position=detailedVisitor.position,
            country_of_origin=detailedVisitor.country_of_origin,
            email=detailedVisitor.email,
            address=detailedVisitor.address,
            mobile_phone=detailedVisitor.mobile_phone
        )
        # Save the Visitor instance
        visitor.save()
        # Create a new Movement instance
        movement = Movement(
            visitor=visitor,
            purpose=purpose,
            devices=devices,
            time_in=timezone.now(),
            comment=comment
        )
        
        # Set the card if selected
        if card_id:
            card = get_object_or_404(Card, pk=card_id)
            movement.card = card
        
        # Save the Movement instance
        movement.save()
        
        # Redirect or render a success message
        detailedVisitor.delete()
        return redirect('records:visitors')
    # Render the details template with the visitor's information
    context = {
        'detailedVisitor': detailedVisitor,
    }
    return render(request, 'records/visitor_list.html', context)
#   detailedVisitor = WaitingList.objects.get(id_passport_nbr=id)
#   template = loader.get_template('records/details.html')
#   context = {
#     'detailedVisitor': detailedVisitor,
#   }
#   return HttpResponse(template.render(context, request))

@login_required
def search_visitors(request):
    query = request.GET.get('query', '')
    visitors = Visitor.objects.filter(first_name__icontains=query)
    context = {'visitors': visitors}
    html = render_to_string('records/search_results.html', context)
    return JsonResponse({'html': html})



def approve_visitor(request, visitor_id):
    # Retrieve the visitor from the WaitingList
    waiting_visitor = WaitingList.objects.get(id_passport_nbr=visitor_id)

    # Create a new Visitor instance with the data from the WaitingList
    visitor = Visitor(
        id_passport_nbr=waiting_visitor.id_passport_nbr,
        first_name=waiting_visitor.first_name,
        surname=waiting_visitor.surname,
        organization=waiting_visitor.organization,
        position=waiting_visitor.position,
        country_of_origin=waiting_visitor.country_of_origin,
        email=waiting_visitor.email,
        address=waiting_visitor.address,
        mobile_phone=waiting_visitor.mobile_phone
    )

    # Save the new Visitor instance
    visitor.save()

    # Delete the corresponding entry from the WaitingList
    waiting_visitor.delete()
    messages.success(request, 'Visitor checked out successfully.')
    return redirect('records:visitors')


def movements(request):
    # movements = Movement.objects.all()
    checked_in_visitors = Movement.objects.filter(time_out__isnull=True)
    checked_out_visitors = Movement.objects.exclude(time_out__isnull=True)

    # Order checked-in visitors by most recent first
    checked_in_visitors = checked_in_visitors.order_by('-id')

    # Order checked-out visitors by most recent checked-out time
    checked_out_visitors = checked_out_visitors.order_by('-time_out')

    movements = list(checked_in_visitors) + list(checked_out_visitors)
    context = {'movements': movements}
    return render(request, 'records/movement.html', context)

records/templates/partials/alerts.html
{% if messages %}
    {% for message in messages%}
        <div id="message" class="container">
           <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
               <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
               <strong>

                   {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error
                   {% else %}
                        {{ message.tags|title }}
                   {% endif %}
               </strong>
                {{ message }}
           </div>
        </div>
    {% endfor %}
    <script>
        setTimeout(function() {
            var messageElement = document.getElementById('message');
            if (messageElement) {
                messageElement.remove();
            }
        }, 5000);  // Delay in milliseconds (e.g., 5000 for 5 seconds)
    </script>
{% endif %}

records/templates/partials/navbar.html
{% load static %}

<!-- <div class="main-wrapper"> -->
    
</div>

records/templates/partials/sidebar.html
{% load static %}

    <!-- ======== sidebar-nav start =========== -->
<aside class="sidebar-nav-wrapper">
    <div class="navbar-logo">
      <a href="{% url 'records:record_visitor' %}">
        <img src="https://bsc.rw/wp-content/uploads/2023/01/BSC-High-res.-vector-logo-01@2x-1-160x69.png" alt="logo" />
      </a>
    </div>
    <nav class="sidebar-nav">
      <ul>
        <li class="nav-item nav-item-has-children">
          <a
            href="#0"
            data-bs-toggle="collapse"
            data-bs-target="#ddmenu_1"
            aria-controls="ddmenu_1"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="icon">
              <svg width="22" height="22" viewBox="0 0 22 22">
                <path
                  d="M17.4167 4.58333V6.41667H13.75V4.58333H17.4167ZM8.25 4.58333V10.0833H4.58333V4.58333H8.25ZM17.4167 11.9167V17.4167H13.75V11.9167H17.4167ZM8.25 15.5833V17.4167H4.58333V15.5833H8.25ZM19.25 2.75H11.9167V8.25H19.25V2.75ZM10.0833 2.75H2.75V11.9167H10.0833V2.75ZM19.25 10.0833H11.9167V19.25H19.25V10.0833ZM10.0833 13.75H2.75V19.25H10.0833V13.75Z"
                />
              </svg>
            </span>
            <span class="text">Dashboard</span>
          </a>
          <ul id="ddmenu_1" class="collapse show dropdown-nav">
            <li>
              <a href="{% url 'records:overview' %}">Overview </a>
            </li>
            <li>
              <a href="{% url 'records:record_visitor' %}" class="active"> Record Visitor </a>
            </li>
            <li>
              <a href="{% url 'records:visitors' %}"> Waiting List </a>
            </li>
            <li>
              <a href="{% url 'records:movements' %}"> Movement </a>
            </li>
          </ul>
        </li>
        
        
        
       
        <span class="divider"><hr /></span>

        
      </ul>
    </nav>
    
  </aside>
  <div class="overlay"></div>